/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package echanelling;

import DBConnector.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rajive Lochchan
 */
public class AdminDoctor extends javax.swing.JFrame {
    Connection con;

    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form AdminDoctor
     */
    public AdminDoctor() {
        initComponents();
        DBConnection objDB = new DBConnection();
        con = objDB.geConnection();
        Updatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spec = new javax.swing.JTextField();
        docname = new javax.swing.JTextField();
        available = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableadmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Doctor Speciality");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        jLabel3.setText("Doctor Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, 20));

        jLabel5.setText("Available Days");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        jLabel6.setText("Doctor Fees");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 30));
        jPanel1.add(spec, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, 30));

        docname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docnameActionPerformed(evt);
            }
        });
        jPanel1.add(docname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, 30));
        jPanel1.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, 30));
        jPanel1.add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, 30));

        jLabel7.setText("Search By Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 110, 30));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Downloads\\icons8-update-filled-50.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 50, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Downloads\\icons8-plus-filled-50.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Downloads\\icons8-cancel-filled-50.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Downloads\\icons8-synchronize-filled-50.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 50, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Add");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 60, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Update");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 200, 50, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Refresh");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 200, 70, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Delete");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 40, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 680, 220));

        tableadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableadmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Pictures\\medilogo.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 290, 120));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Downloads\\icons8-long-arrow-left-80.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Pictures\\admindoc1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        setSize(new java.awt.Dimension(1227, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void docnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docnameActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
  try {
            String sql = "select * from Finddoctor2 where Doctorname =?";
            pst = con.prepareStatement(sql);
            pst.setString(1, search.getText());

            rs = pst.executeQuery();
            if (rs.next()) {

                
                
                String add1 = rs.getString("Doctorspec").trim();
                spec.setText(add1);
                String add2 = rs.getString("Doctorname".trim());
                docname.setText(add2);
                String add3 = rs.getString("Availableday").trim();
                available.setText(add3);
                String add4 = rs.getString("Doctorfees").trim();
                fee.setText(add4);
               
        

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_searchKeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
 
        if (docname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Doctor Name Field is empty", "Adding Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } else if (spec.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Doctor Speciality Field is empty", "Adding Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } else if (available.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Availability Field is empty", "Adding Unsuccesfull", JOptionPane.ERROR_MESSAGE);

        } else if (fee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Fees Field empty", "Adding Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        }
        try {
                PreparedStatement stat = con.prepareStatement("insert into Finddoctor2 values (?,?,?,?) ");
                int row = 0;

                stat.setString(1, spec.getText());
                stat.setString(2, docname.getText());
                stat.setString(3, available.getText());
                stat.setString(4, fee.getText());
              
                row = stat.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(null, "Doctor Details Added Sucessfully", "Registeration sucessful", JOptionPane.INFORMATION_MESSAGE);
                   
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "An error occured during the execution\n" + ex, "Information not submitted", JOptionPane.ERROR_MESSAGE);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
this.dispose();
AdminDoctor obj= new AdminDoctor();
obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
try {
            PreparedStatement stat = con.prepareStatement("UPDATE Finddoctor2 set Doctorname=?,Availableday=?, Doctorfees=? WHERE Doctorspec=?");
            int row = 0;

            stat.setString(1, docname.getText().trim());
            stat.setString(2, available.getText().trim());
            stat.setString(3, fee.getText());
            stat.setString(4, spec.getText());
                                                             // TODO add your handling code here:

            row = stat.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(null, "Doctor Details have been UPDATED", "Registeration sucessful", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An error occured during the execution\n" + ex, "Information not submitted", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        AdminAccount  obj = new AdminAccount();
        obj.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
int p = JOptionPane.showConfirmDialog(null, "Do you really want to Delete","Delete",JOptionPane.YES_NO_OPTION);

if (p==0) {
    
    String sql ="DELETE from Finddoctor2 where Doctorname=?";
    
    try{
        pst =con.prepareStatement(sql);
        
        pst.setString(1, docname.getText());
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "DELETED");
       
    }
    
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    public void Updatetable() {

        String sql = " select * from Finddoctor2 ";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tableadmin.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField available;
    private javax.swing.JTextField docname;
    private javax.swing.JTextField fee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTextField spec;
    private javax.swing.JTable tableadmin;
    // End of variables declaration//GEN-END:variables
}
