/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package echanelling;

import DBConnector.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajive Lochchan
 */
public class Payment extends javax.swing.JFrame {

    Connection con;

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        DBConnection objDB = new DBConnection();
        con = objDB.geConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb = new javax.swing.JComboBox();
        mm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        holdername = new javax.swing.JTextField();
        cardnum = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        yy = new javax.swing.JTextField();
        cvv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Card Type---", "Visa", "Master", "Credit Card", "Genie", " " }));
        getContentPane().add(cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 20));

        mm.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });
        getContentPane().add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 20));

        jLabel1.setText("/");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 10, 20));
        getContentPane().add(holdername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 30));

        cardnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnumActionPerformed(evt);
            }
        });
        getContentPane().add(cardnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 220, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 220, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 20));

        yy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        yy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yyActionPerformed(evt);
            }
        });
        getContentPane().add(yy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 50, 20));
        getContentPane().add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("CVV*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 40, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*YY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 20, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*MM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Pictures\\pre.jpg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 210, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Pictures\\clear.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 80, 50));

        txtpay.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Pictures\\Pay-Now.png")); // NOI18N
        txtpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpayMouseClicked(evt);
            }
        });
        getContentPane().add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajive Lochchan\\Pictures\\payment.PNG")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*MM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, -1));

        setSize(new java.awt.Dimension(607, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void cardnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnumActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void yyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yyActionPerformed

    private void txtpayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpayMouseClicked

        String Cardnumber = cardnum.getText().toString().trim();
        String Cvv = cvv.getText().toString().trim();

        if (cmb.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Card Type Field is empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } else if (cardnum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Card Number Field is empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        }
        if (Cardnumber.length() != 16) {

            JOptionPane.showMessageDialog(null, "Invalid Card Number", "Registration Unsuccesfull", JOptionPane.ERROR_MESSAGE);

        } else if (mm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Month Field is empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);

        } else if (yy.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Year  Field empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } else if (cvv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "CVV Field empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        }
        if (Cvv.length() != 3) {

            JOptionPane.showMessageDialog(null, "Invalid CVV Number", "Registration Unsuccesfull", JOptionPane.ERROR_MESSAGE);

        } else if (holdername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Card Holder Name Field empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } else if (email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Email Field empty", "Booking Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                PreparedStatement stat = con.prepareStatement("insert into PatientPayment values (?,?,?,?,?,?,?) ");
                int row = 0;

                stat.setString(1, cmb.getSelectedItem().toString());
                stat.setString(2, cardnum.getText());
                stat.setString(3, mm.getText());
                stat.setString(4, yy.getText());
                stat.setString(5, cvv.getText());
                stat.setString(6, holdername.getText());
                stat.setString(7, email.getText());

                row = stat.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(null, "Payment Received Sucessfully", "Registeration sucessful", JOptionPane.INFORMATION_MESSAGE);
                    PatientAccount obj = new PatientAccount();
                    obj.setVisible(true);
                    this.dispose();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "An error occured during the execution\n" + ex, "Information not submitted", JOptionPane.ERROR_MESSAGE);
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txtpayMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        cardnum.setText(null);
        mm.setText(null);
        yy.setText(null);
        cvv.setText(null);
        holdername.setText(null);
        email.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Patapp obj = new Patapp();
        obj.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardnum;
    private javax.swing.JComboBox cmb;
    private javax.swing.JTextField cvv;
    private javax.swing.JTextField email;
    private javax.swing.JTextField holdername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mm;
    private javax.swing.JLabel txtpay;
    private javax.swing.JTextField yy;
    // End of variables declaration//GEN-END:variables
}
